services:
  - type: web
    name: telegram-powerbi-bot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python bot.py"
    plan: free
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
